name: fetch-data
on:
  schedule:
    - cron: "0 0 */2 * *" # Schedule to run every 2 days at midnight (UTC)
jobs:
  my-job:
    name: my-job
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun index.ts
      
